framework:
    secret: '%env(APP_SECRET)%'
    validation: { enabled: true }
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session:
        handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
