security:
    encoders:
      App\Entity\User:
        algorithm: bcrypt
    providers:
        our_db_provider:
          entity:
            class: App\Entity\User
            property: username
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    firewalls:
      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
      main:
          user_checker: App\Security\UserChecker
          anonymous: ~
          form_login:
            login_path: login
            check_path: login
          logout:
              path: /logout
              target: /login
          pattern:    ^/
          http_basic: ~
          remember_me:
                secret: '%kernel.secret%'
                secure: true
                path: /
          provider: our_db_provider
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

        - { path: ^/contact, roles: ROLE_ADMIN }
        - { path: ^/contact/remove, roles: ROLE_ADMIN }

        - { path: ^/blog/add, roles: ROLE_ADMIN }
        - { path: ^/blog/edit, roles: ROLE_ADMIN }
        - { path: ^/blog/delete, roles: ROLE_ADMIN }

        - { path: ^/forum, roles: ROLE_ADMIN }
        - { path: ^/forum/add, roles: ROLE_ADMIN }
        - { path: ^/foru/edit, roles: ROLE_ADMIN }

        - { path: ^/category, roles: ROLE_ADMIN }
        - { path: ^/category/add, roles: ROLE_ADMIN }
        - { path: ^/category/edit, roles: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
